const fs=require('fs'); const path=require('path');
const root=path.resolve(__dirname,'..');
const base='https://errorlookup.com';
const codes=JSON.parse(fs.readFileSync(path.join(root,'data/codes.json'),'utf8'));
const guideDirs=fs.readdirSync(path.join(root,'guides'));
const guideMap=new Map(guideDirs.map(d=>[Number(d.split('-')[0]),d]));
const classMap={1:'Informational',2:'Success',3:'Redirection',4:'Client Errors',5:'Server Errors'};
const catPath={1:'/common/informational/',2:'/common/success/',3:'/common/redirect-codes/',4:'/common/client-errors/',5:'/common/server-errors/'};
const enrich=codes.map(c=>{
 const code=Number(c.code), cls=Math.floor(code/100);
 const slug=guideMap.get(code)||`${code}-${String(c.title).toLowerCase().replace(/\(.*?\)/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}`;
 const phrase=c.title.replace(/\s*\(.*\)$/,'').trim();
 return { ...c, code, slug, pathGuide:`/guides/${slug}/`, pathStatus:`/status/${code}/`, phrase, category:classMap[cls], class:cls,
 summary:`HTTP ${code} ${phrase} is a ${classMap[cls].toLowerCase()} status code used in HTTP responses.`,
 meaning:`${phrase} indicates how the server handled the request and what the client should do next.`,
 causes:[`Request matched conditions for ${code}.`,`Application or upstream behavior returned this status.`],
 fixes:[`Inspect logs and response headers for ${code}.`,`Apply handling based on ${classMap[cls].toLowerCase()} semantics.`],
 examples:{request:'GET /resource HTTP/1.1\nHost: example.com',response:`HTTP/1.1 ${code} ${phrase}\nContent-Type: text/plain`},
 related:[code-1,code+1].filter(n=>codes.some(x=>x.code===n)).slice(0,3), aliases:[phrase.toLowerCase()],
 keywords:[`${code}`,phrase.toLowerCase(),classMap[cls].toLowerCase()], compare:[], indexable:true, official:!phrase.toLowerCase().includes('unassigned')&&!phrase.toLowerCase().includes('unused'), notes:'', rfc:c.reference, iana_name:phrase };
});
fs.writeFileSync(path.join(root,'data/codes.json'),JSON.stringify(enrich,null,2)+'\n');

const head=(title,desc,url,extra='')=>`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title><meta name="description" content="${desc}"><link rel="canonical" href="${base}${url}"><meta property="og:title" content="${title}"><meta property="og:description" content="${desc}"><meta property="og:type" content="website"><meta property="og:url" content="${base}${url}"><meta name="twitter:card" content="summary">${extra}<link rel="stylesheet" href="/assets/css/site.css"><script defer src="/assets/js/theme.js"></script><script defer src="/assets/js/site.js"></script><script defer src="/assets/js/search.js"></script></head><body><div data-include="/partials/header.html"></div>`;
const foot=`<div data-include="/partials/footer.html"></div></body></html>`;
const wrap=(content)=>`<main class="container">${content}</main>`;

function write(rel,html){const out=path.join(root,rel);fs.mkdirSync(path.dirname(out),{recursive:true});fs.writeFileSync(out,html);}

const websiteLd=`<script type="application/ld+json">${JSON.stringify({"@context":"https://schema.org","@type":"WebSite",name:"ErrorLookup",url:base,potentialAction:{"@type":"SearchAction",target:`${base}/?q={query}`,"query-input":"required name=query"}})}</script>`;
write('index.html',head('HTTP Status Code Lookup & HTTP Error Code Reference | ErrorLookup','Lookup HTTP status codes, compare 301 vs 302 and 401 vs 403, and troubleshoot 404 and 500 errors with developer-focused guides.','/',websiteLd)+wrap(`
<section class="hero"><h1>HTTP Status Code Lookup for Developers</h1><p>Search and troubleshoot HTTP error codes fast. Use this index for status meanings, causes, and fixes.</p><div data-include="/partials/search.html"></div></section>
<div class="grid"><div>
<section class="section"><h2>What HTTP Status Codes Mean</h2><p>Status codes are server responses that explain request outcomes across informational, success, redirection, client error, and server error classes.</p></section>
<section class="section"><h2>Common HTTP Errors</h2><ul><li><a href="/guides/404-not-found/">404 Not Found meaning</a></li><li><a href="/guides/500-internal-server-error/">500 Internal Server Error fixes</a></li><li><a href="/guides/401-unauthorized/">401 Unauthorized</a></li><li><a href="/guides/403-forbidden/">403 Forbidden</a></li></ul></section>
<section class="section"><h2>Status Code Categories</h2><ul><li><a href="/common/informational/">1xx Informational</a></li><li><a href="/common/success/">2xx Success</a></li><li><a href="/common/redirect-codes/">3xx Redirect Codes</a></li><li><a href="/common/client-errors/">4xx Client Error Codes</a></li><li><a href="/common/server-errors/">5xx Server Error Codes</a></li></ul></section>
<section class="section"><h2>Popular Comparisons</h2><ul><li><a href="/compare/301-vs-302/">301 vs 302</a></li><li><a href="/compare/401-vs-403/">401 vs 403</a></li><li><a href="/compare/403-vs-404/">403 vs 404</a></li></ul></section>
<section class="section"><h2>Developer Resources</h2><ul><li><a href="/status-codes/">All HTTP status codes</a></li><li><a href="/guides/200-ok/">200 OK guide</a></li><li><a href="/guides/301-moved-permanently/">301 Moved Permanently guide</a></li><li><a href="/guides/302-found/">302 Found guide</a></li></ul></section>
</div><aside><div data-include="/partials/ads.html"></div></aside></div>`)+foot);

const grouped={1:[],2:[],3:[],4:[],5:[]}; enrich.forEach(c=>grouped[c.class].push(c));
const hubSections=[1,2,3,4,5].map(k=>`<section class="card"><h2>${k}xx ${classMap[k]}</h2><ul>${grouped[k].map(c=>`<li><a href="${c.pathStatus}">${c.code}</a> · <a href="${c.pathGuide}">${c.phrase}</a> <span class="muted">${c.summary}</span></li>`).join('')}</ul></section>`).join('');
write('status-codes/index.html',head('All HTTP Status Codes (1xx-5xx) | ErrorLookup','Browse the full HTTP status code list by class, with links to numeric pages and practical troubleshooting guides.','/status-codes/')+wrap(`<nav class="breadcrumbs" data-breadcrumbs></nav><h1>HTTP Status Codes Reference</h1>${hubSections}`)+foot);

const catMeta={1:['informational','Informational HTTP Status Codes (1xx)'],2:['success','Success HTTP Status Codes (2xx)'],3:['redirect-codes','Redirect HTTP Status Codes (3xx)'],4:['client-errors','Client Error HTTP Status Codes (4xx)'],5:['server-errors','Server Error HTTP Status Codes (5xx)']};
for(const k of [1,2,3,4,5]){const [slug,title]=catMeta[k];const list=grouped[k].map(c=>`<li><a href="${c.pathStatus}">${c.code} ${c.phrase}</a> — ${c.summary} <a href="${c.pathGuide}">Guide</a></li>`).join('');
write(`common/${slug}/index.html`,head(`${title} | ErrorLookup`,`${title} with meanings, short summaries, fixes, and links to full guides.`,catPath[k])+wrap(`<nav class="breadcrumbs" data-breadcrumbs></nav><h1>${title}</h1><p>${classMap[k]} responses indicate ${k===1?'protocol progress':k===2?'successful processing':k===3?'resource movement and caching':k===4?'request-side issues':'server-side failures'}.</p><section class="card"><h2>Code List</h2><ul>${list}</ul></section><section class="card"><h2>FAQ</h2><h3>Why does this category matter?</h3><p>It helps triage whether you should fix the client, routing, auth, or server logic.</p><h3>Where can I browse all classes?</h3><p>Use the <a href="/status-codes/">master status code hub</a>.</p></section>`)+foot);
}

function comparePage(slug,a,b){const A=enrich.find(c=>c.code===a),B=enrich.find(c=>c.code===b);write(`compare/${slug}/index.html`,head(`${a} vs ${b}: ${A.phrase} vs ${B.phrase} | ErrorLookup`,`Compare HTTP ${a} and ${b} with side-by-side behavior, use-cases, SEO implications, and troubleshooting guidance.`,`/compare/${slug}/`)+wrap(`<nav class="breadcrumbs" data-breadcrumbs></nav><h1>${a} vs ${b}: ${A.phrase} vs ${B.phrase}</h1><p>Both codes are common but serve different semantics in production traffic.</p><div class="table-wrap"><table><tr><th>Aspect</th><th>${a}</th><th>${b}</th></tr><tr><td>Meaning</td><td>${A.meaning}</td><td>${B.meaning}</td></tr><tr><td>When to use</td><td>Use when behavior aligns with ${A.phrase.toLowerCase()}.</td><td>Use when behavior aligns with ${B.phrase.toLowerCase()}.</td></tr><tr><td>SEO impact</td><td>Review cache and crawl implications.</td><td>Review cache and crawl implications.</td></tr></table></div><section class="card"><h2>FAQ</h2><h3>Which one should I return?</h3><p>Return the status that most accurately describes intent and client action.</p></section><p>Related: <a href="${A.pathGuide}">${a} guide</a> · <a href="${B.pathGuide}">${b} guide</a></p>`)+foot);}
comparePage('301-vs-302',301,302);comparePage('401-vs-403',401,403);comparePage('403-vs-404',403,404);

for(const c of enrich){
 const breadcrumbLd=(name,url)=>`<script type="application/ld+json">${JSON.stringify({"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Home",item:base+'/'},{"@type":"ListItem",position:2,name:url.includes('/guides/')?'Guides':'Status',item:base+(url.includes('/guides/')?'/status-codes/':'/status-codes/')},{"@type":"ListItem",position:3,name:`${c.code} ${c.phrase}`,item:base+url}]})}</script>`;
 const faq={"@context":"https://schema.org","@type":"FAQPage",mainEntity:[{"@type":"Question",name:`What does HTTP ${c.code} mean?`,acceptedAnswer:{"@type":"Answer",text:c.meaning}},{"@type":"Question",name:`How do I fix HTTP ${c.code}?`,acceptedAnswer:{"@type":"Answer",text:c.fixes.join(' ')}}]};
 const art={"@context":"https://schema.org","@type":"TechArticle",headline:`HTTP ${c.code} ${c.phrase}`,description:c.summary,author:{"@type":"Organization",name:"ErrorLookup"}};
 write(`status/${c.code}/index.html`,head(`HTTP ${c.code} ${c.phrase}: Meaning & Lookup | ErrorLookup`,`HTTP ${c.code} lookup page with quick meaning, category, examples, and links to full remediation guidance.`,c.pathStatus,breadcrumbLd(c.phrase,c.pathStatus))+wrap(`<nav class="breadcrumbs" data-breadcrumbs></nav><article data-related-code="${c.code}"><h1>HTTP ${c.code} ${c.phrase}</h1><p class="muted">${c.category}</p><section class="card"><h2>Definition</h2><p>${c.meaning}</p></section><section class="card"><h2>Reference</h2><p>${c.rfc}</p></section><section class="card"><h2>Example Response</h2><pre>${c.examples.response}</pre></section><section class="card"><h2>Related status codes</h2><div id="related-links"></div></section><p><a href="${c.pathGuide}">Read the full guide for HTTP ${c.code}</a></p></article><script defer src="/assets/js/render-related.js"></script>`)+foot);
 write(`guides/${c.slug}/index.html`,head(`HTTP ${c.code} ${c.phrase}: Meaning, Causes, and Fixes | ErrorLookup`,`Understand HTTP ${c.code} ${c.phrase}, why it happens, common causes, and practical fixes for developers and operators.`,c.pathGuide,`${breadcrumbLd(c.phrase,c.pathGuide)}<script type="application/ld+json">${JSON.stringify(art)}</script><script type="application/ld+json">${JSON.stringify(faq)}</script>`)+wrap(`<nav class="breadcrumbs" data-breadcrumbs></nav><article data-related-code="${c.code}"><h1>HTTP ${c.code} ${c.phrase}</h1><p>${c.summary}</p><section class="card"><h2>What it means</h2><p>${c.meaning}</p></section><section class="card"><h2>Why it happens</h2><p>${c.causes[0]} ${c.causes[1]}</p></section><section class="card"><h2>Common causes</h2><ul>${c.causes.map(x=>`<li>${x}</li>`).join('')}</ul></section><section class="card"><h2>How to fix it</h2><ul>${c.fixes.map(x=>`<li>${x}</li>`).join('')}</ul></section><section class="card"><h2>Example request/response</h2><pre>${c.examples.request}\n\n${c.examples.response}</pre></section><section class="card"><h2>Browser/dev/server context</h2><p>Validate behavior in browser DevTools, application logs, and upstream proxy/server telemetry.</p></section><section class="card"><h2>Related status codes</h2><div id="related-links"></div></section><section class="card"><h2>FAQ</h2><h3>Is HTTP ${c.code} an error?</h3><p>${c.class>=4?'Yes, it indicates a failure condition.':'Not always; it may indicate normal protocol flow.'}</p><h3>Is this code official?</h3><p>${c.official?'Yes, this is an officially recognized status phrase.':'This code is unassigned/unused or temporary; treat carefully in production.'}</p></section></article><script defer src="/assets/js/render-related.js"></script>`)+foot);
}
